============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0 -- /opt/homebrew/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/andreytarasov/AAA_python_final
plugins: cov-4.0.0
collecting ... collected 8 items

tests.py::test_pizza[some_pizza0-expected_value0] PASSED                 [ 12%]
tests.py::test_pizza[some_pizza1-expected_value1] PASSED                 [ 25%]
tests.py::test_pizza[some_pizza2-expected_value2] PASSED                 [ 37%]
tests.py::test_pizza[some_pizza3-expected_value3] PASSED                 [ 50%]
tests.py::test_bake PASSED                                               [ 62%]
tests.py::test_beautiful_bake PASSED                                     [ 75%]
tests.py::test_beautiful_delivery PASSED                                 [ 87%]
tests.py::test_beautiful_pickup FAILED                                   [100%]

=================================== FAILURES ===================================
____________________________ test_beautiful_pickup _____________________________

capfd = <_pytest.capture.CaptureFixture object at 0x101fac880>

    def test_beautiful_pickup(capfd):
        pizza.beautiful_pickup(pizza.Pepperoni)
>       out, = capfd.readouterr()
E       ValueError: too many values to unpack (expected 1)

tests.py:82: ValueError
=========================== short test summary info ============================
FAILED tests.py::test_beautiful_pickup - ValueError: too many values to unpac...
========================= 1 failed, 7 passed in 0.02s ==========================
